[package]
name = "bg3_lib"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bincode = "1.3.3"
flate2 = "1.0.28"
lz4_flex = "0.11.2"
serde = { version = "1.0.195", features = ["derive"] }
serde-big-array = "0.5.1"
uuid = "1.6.1"
