[package]
name = "bg3_ui"
version.workspace = true
authors.workspace = true
edition.workspace = true


[dependencies]
egui = { version = "0.26.2", features = ["log"] }
egui_extras = { version = "0.26.2", features = ["all_loaders"] }
image = { version = "0.24.8", features = ["webp"] }
eframe = "0.26.2"
rfd = "0.13.0"
bg3_lib.workspace = true
