[package]
name = "bg3_ui"
version.workspace = true
authors.workspace = true
edition.workspace = true


[dependencies]
egui = { version = "0.27.2", features = ["log"] }
egui_extras = { version = "0.27.2", features = ["all_loaders"] }
image = { version = "0.25.1", features = ["webp"] }
eframe = { version = "0.27.2", features = ["wgpu"] }
rfd = "0.14.1"
bg3_lib.workspace = true
